### ISSUE TITLE
Enable sorting by resource type, publisher, dating, title

### ISSUE THREAD

**Issue by alessiabardi** [ARIADNE-Infrastructure/Index#3]
It was reported that the fields for sorting are score and issued.
We would like the portal to offer the sorting also on the resource type, publisher, dating, and title fields.
I need to check why with the current index model is not possible and change it.
I guess a background complete re-indexing is required for the change to be applied to already indexed records.

**Comment by jockelarsson** [comment]
* Adding a raw field to title will be perfect. 
* About resourceType yes it's probably ariadneSubject that should be sorted on instead. But I think it sounds like a good idea to add a raw field to resourceType so we can add a filter/switch for datasets/collections.
* I'm not sure what type of dating sort they want, but good that temporal has sortable from & until. That's probably enough

**Comment by alessiabardi** [comment]
I updated the staging index. You can now sort by:
- title.text.raw
- resourceType.raw

Let me know if it is ok and if I can introduce the same changes also in the public opensearch mapping.

**Comment by jockelarsson** [comment]
It works but I noticed when sorting on title the results gets sorted in a weird order. I think it's because title is a multiple field with different languages. I believe we only want to sort on the english title not sure if that's possible. Maybe it has to be a different field instead of raw, with just the english title?

**Comment by jockelarsson** [comment]
I'm closing this since we're skipping title sort & not having a filter for resourceType
